### ISSUE TITLE
师傅您好，这样的图片格式也无法识别

### ISSUE THREAD

**Issue by ltfafei** [f0ng/captcha-killer-modified#10]
![image](https://user-images.githubusercontent.com/43526141/173160829-1c5ab19b-b536-4643-861c-b52a40bef1b8.png)

**Comment by f0ng** [comment]
看你这个截图，有识别的结果，只是识别结果不准确，验证码混淆程度过高，估计得自行训练了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月11日(周六) 上午7:03
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [f0ng/captcha-killer-modified] 师傅您好，这样的图片格式也无法识别 (Issue #10)

**Comment by ltfafei** [comment]
好的吧，机器学习不会啊

**Comment by DreamAndSun** [comment]
![image](https://user-images.githubusercontent.com/86992999/176646103-3507c754-2b16-4f8a-95e1-49cf36fcee6a.png)
师傅 这个也无法识别  能不能给返回数据变成键值对的形式，关键字输入键就可以了

**Comment by f0ng** [comment]
已经考虑到过了
https://github.com/f0ng/captcha-killer-modified#%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97
【2022-3-24】更新的内容

**Comment by f0ng** [comment]
图片加载不出来，加微信吧，f-f0ng

**Comment by f0ng** [comment]
原因在于base64编码中存在`\n`旧版本无法识别，`0.16`版本增加对`\n`的处理
