### ISSUE TITLE
爆破问题

### ISSUE THREAD

**Issue by longzaizai001** [f0ng/captcha-killer-modified#12]
验证码可以识别
intruder的cookie要和captcha-killer的cookie也一致
intruder的线程调为1
爆破时 响应包还是提示验证码错误

**Comment by f0ng** [comment]
验证码识别是正确的吗

**Comment by longzaizai001** [comment]
验证码识别是正确的

**Comment by f0ng** [comment]
那不太清楚了，这个具体得去原插件找原因了，我只修改兼容了新版本
