### ISSUE TITLE
TypeError: DdddOcr.classification() got an unexpected keyword argument 'img_base64'  识别的时候报错，最新版ddddocr

### ISSUE THREAD

**Issue by wgetnz** [f0ng/captcha-killer-modified#14]
return web.Response(text=ocr.classification(img_base64=await request.text()))
TypeError: DdddOcr.classification() got an unexpected keyword argument 'img_base64'

**Comment by TouchNothing** [comment]
codereg.py
return web.Response(text=ocr.classification(img_base64=await request.context()))  改成
img_base64 = await request.text()
return web.Response(text=ocr.classification(img_base64))

**Comment by TouchNothing** [comment]
试试修改codereg.py，17行左右
return web.Response(text=ocr.classification(img_base64=await request.text())) 改成
img_base64=await request.text()
return web.Response(text=ocr.classification(img_base64))

**Comment by wgetnz** [comment]
> 试试修改codereg.py，17行左右 return web.Response(text=ocr.classification(img_base64=await request.text())) 改成 img_base64=await request.text() return web.Response(text=ocr.classification(img_base64))

完美，正常了
