### ISSUE TITLE
无法识别验证码（已解决）

### ISSUE THREAD

**Issue by li-baige** [f0ng/captcha-killer-modified#15]
按照步骤往下走，无法识别出验证码
![Xnip2022-09-14_09-53-35](https://user-images.githubusercontent.com/76275424/190040987-56bfe3bf-71e0-4cbd-a0af-c1be727499f7.jpg)

**Comment by f0ng** [comment]
加微信吧，f-f0ng

**Comment by li-baige** [comment]
Burp版本如果太新，或者jdk版本与Burp版本不适配也会出错，经过测试

**Comment by f0ng** [comment]
问题在于burp版本太新，可能jdk版本配置有问题，更换2021 burp正常
