### ISSUE TITLE
大佬，有添加返回体多个参数的用法吗？

### ISSUE THREAD

**Issue by Explore-c** [f0ng/captcha-killer-modified#18]
遇到一个，需要两个参数的
![image](https://user-images.githubusercontent.com/46821530/201609704-ee124e3f-3135-4f2f-bcaa-7d31c2241632.png)

**Comment by f0ng** [comment]
这种情况可以去看看burp的intruder文章，百度关键字`burp intruder token`

**Comment by f0ng** [comment]
验证码和token同时出现暂时无法解决

**Comment by f0ng** [comment]
`0.17`版本添加校验参数功能
