### ISSUE TITLE
Returns the verification code identification directly

### ISSUE THREAD

**Issue by angel1374** [f0ng/captcha-killer-modified#19]
![图片](https://user-images.githubusercontent.com/71721281/203612791-d3862b3d-9343-4380-b69a-4fd2abc19e87.png)
Returns the verification code identification directly,A lack of recognition in the writing class

**Comment by f0ng** [comment]
what？

**Comment by f0ng** [comment]
sorry,if you can describe your problem clearly, you can reopen it
