### ISSUE TITLE
返回的base64字符串带URL编码，无法识别

### ISSUE THREAD

**Issue by yinanzhaobaima** [f0ng/captcha-killer-modified#20]
求加简单的解码识别功能，如URL解码

{"src":"data:image/.jpg;base64,%2F9j%2F4AAQSkZJRgABAQAAAQABAAD%2F2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL%2F2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL%2FwAARCAAjAFADASIAAhEBAxEB%2F8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL%2F8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4%2BTl5ufo6erx8vP09fb3%2BPn6%2F8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL%2F8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3%2BPn6%2F9oADAMBAAIRAxEAPwD3CO0R7GMpFDuMPUoM7sDBzg%2B%2FY%2F42fslt%2FwA%2B8X%2FfAplqBHYxukeWMasQuAWO0frwBzUeqSgWptlLedc5iQK5Q8jk7gQRgc5HNCV2JyUVdj%2FsNm84k%2BzrvjBTG0hTnB6dD0HPOOQOpp4tbclgbWMYOASi88dR%2FntVHSJbm90zM1wwkWYjzEAyyqw45BGDgg98Hgg81LNd3sUhjg0%2BWcAkl3kVO56ev%2Bc80p%2B47MVN%2B0Sa6j7gWVovmXEVtFBlV819qgEnAznHU7QOpJbpThaIJVBtbZoyGLOFwQcjaAuDnjOTkcgcc8UhqN%2B97FayWawmUHJWUOyD%2B90x%2BdWru9fT7KLzts924ChYkKiR8c4GTgficeppQfO9CpvkV5Fj7Jbf8%2B8X%2FfAqN7GKW2ZPKjhkdCN8aKShI6jcuDj3GPas9tZuLR4V1G08gOceYh3K3HTrwc46%2BlasauVUyyK7B2ZTGCo2knaCMnOARnsSM4HAFyi0RCpGe3QaLK3BYmGM5OQCi8cdBx%2FnNR3VrbraTMsEQIjYghBxxVMakyRLBptnPeJEoXzHkOOOPvtksfXqTU8l076YTPbywySqy7NpbB2k8kZ2jg8nHOB1IyixftdtpmjxTzfu4gqZ2ITyxHYD1PJ%2BpPesZ9aLRzX1tE0shGAWJ2Qg4AHuxwCQP6HO3HaQ3WnwpcIJU2o4VwMAgD%2FP4ntT2sYneLcAYYm3pFtwFbjGMenPXPJ9quEox3RhVhUm9Hb%2FADKeg29zBY%2BRdRGMwvlAOMgjnJBO7ksegxkDGRkpq2owQsIUiL6gp%2F0TfbMyrKyOAwPAxjcCQwwDgkbhnSSKIxMip%2B7OVKMDjA%2BXAB6Djtx371TsoWfUru5mmhklQiEJE2fKGA2G9CQyn8fespyk3p1NqcVGKXRC6fbSWshaZGea4BklmyMIRj5OTnu2MDGBzjjJfXVrbTRyTwu86EiFUXcxyBkqAfw59KuSM8SllSSYs6jau0bQSATzjgcse%2FXGeBWHDoN6L6eWXUn2uARJH8rk5OQc5wANuMHnJ4GObpRila9iK05v4Ve%2F4CzDUtUsIobzTRECFaYRyqxJwCQucd8jnHH5Va1uabyobK2Baa4bBVSB8gHzc9qtWVtcW29ZrtrhONm9QGX1ye9RX1vPOba5tgVuYidqyH5QCOQ2D7Y47%2B1OT6LYIK3vPd%2F10M2S1u3092N29pDCjKiRKUAKcHcWwxyc4IGCBkdRm7YvdyeG1e9ZWuGgJYqu0HjrjJpsenXl3OJtTmRoxJuW1CgovygdeCeRnnPU%2B2L06FLCfccsYyWIzjO3HAJOBx0qDQwk1K7jRUWbCqMAbR0%2FKgaldhy4kG4gAtsXJA6dvc%2FnRRSGL%2Fat7%2Fz2%2FwDHV%2FwpDqd2xUmUEqcqSi8HGOOPc0UUAH9p3ZcOZRuAIB2LkA9e3sPypf7Vvf8Ant%2F46v8AhRRQAf2re%2F8APb%2Fx1f8ACj%2B1b3%2Fnt%2F46v%2BFFFAENpdz2NlBZ2z7III1ijTAO1VGAMnk8CpX1K7kRkabKsMEbR0%2FKiigD%2F9k%3D"}

**Comment by f0ng** [comment]
此问题出在`data:image/.jpg`的`.`以及url解码问题，`0.19`版本修复该问题
