### ISSUE TITLE
Can someone explain to me how to use the extension with gsa captcha breaker?

### ISSUE THREAD

**Issue by 5C3P73ROF** [f0ng/captcha-killer-modified#21]
please help

**Comment by f0ng** [comment]
hello，please look at https://gv7.me/articles/2019/burp-captcha-killer-usage/

**Comment by 5C3P73ROF** [comment]
I have already read that, what happens to me is that gsa captcha breaker tells me incomplete image data

**Comment by f0ng** [comment]
Can u give me the request？maybe the response is not a picture.

**Comment by 5C3P73ROF** [comment]
I already solved the problem using another api
