### ISSUE TITLE
【BUG】 点击获取无反应

### ISSUE THREAD

**Issue by Deep0** [f0ng/captcha-killer-modified#23]
Burp Suite 2023.2 版本
自启动JDK 17
环境未设置JDK
<img width="992" alt="图片" src="https://user-images.githubusercontent.com/25843151/229678370-d540c991-c776-486e-8897-327f09a4b4da.png">

点击获取无反应，Logger无获取验证码请求。

**Comment by f0ng** [comment]
大概率是jdk版本和burp版本原因或者是http版本的问题，可以更换试试，不算是bug

**Comment by passwa11** [comment]
POST
```
POST /portal/user/getCaptcha HTTP/1.1
Host: xx.xx.xx.xx
Content-Length: 0
ChildAuthorization: 
Accept: application/json, text/plain, */*
X-Requested-With: XMLHttpRequest
Accept-Language: zh-CN
Authorization: 
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.178 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Accept-Encoding: gzip, deflate
Connection: close


```
resp
```
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 11 Apr 2023 04:10:12 GMT
Content-Type: application/json;charset=UTF-8
Content-Length: 6785
Connection: close
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,OPTIONS,PUT,DELETE
Access-Control-Allow-Headers: Content-Type,Content-Length,Accept-Encoding,X-Requested-with, Origin

{"data":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABkAMgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigAoqKK5gmeRIpo5HjOHVGBKn0Pp0NS0AUtQl1GDy5bG3huUXPnQM+yRhwco33S3BG1sAlh8645fYXy38DSCC5gZG2PHcRFGVgBkc8MOfvKSp7E1aopiGSypDGZJDtQdTjp7n29+1OR1kRXRgysMhgcgj1paqvZhHaW1YQSsctwSjE9SygjJ9+DwOccVLuTJyTuldFqq9/a/bbGa28x4y68OkjoVPUHKMrYz1AIyOO9NS7ZHWO6hMLMcBgd0bH03Y47D5gMk4GatUaMcJp6xZyn/CPXcHDpc3SryZItdvIncf7MbOQD2GXwfUZ4Psemx8XUHie3fqE+23k2R65ikdfwJz7dM9XVS906C/2ec90uzOPIupYc5x12MM9O9Z+ztsbxq1L6zf9fMXT7iyuLRfsF3HcwxYj3pP5vIA4LZJJxjqc81arJ/4R2y/576n/wCDS5/+OVbstOgsN/kvdNvxnz7qWbGM9N7HHXtWiv1FJQtdNt+n/BLdFFFMzCiis270K0vLl7iWbUFd8ZEOo3ES8DHCo4UdOwqoqLfvO34/qgNKisb/AIRiw/5+NW/8G91/8cqS0s5tFSRYmnu7RnLnzp5JZo8+hctuHsMYA6MTzUlTt7rd/T/gscU2atFMhmjuIllibcp9sEHoQQeQQeCD0p9ZiatowooooAr3KXb7fss8EWM7vNhMmfTGGXHf1oqxRVKTQrBRRRUjIbiztrrb9ot4ZtudvmIGxn0zUP8AZdqOIxNEvZIZ3jUfRVIA/KrlRXCyNEBFnd5iE4OONwz+maTBuyIPsl0nzR6lMzDoJo0ZfxChT+oqxEXVFSaSN5cEkou0HnsCT6jvUlMaMM6PkhkJxjvkdD7d/wABQ79AH0UUUwKU+mQyzNcRNJa3LY3TwEKzcY+YEFX44G4HGeMVH9qv7Ti6tPtKDnz7QdB3LRsdwx2ClycHgcCtGincViG1u7e8jMlvKsiqdrAdUburDqrDPIPIqO/vPsMCztHuhDqJWzjy0Jxv+gJBOSMLk9sFLrTre6kExDRXKjatxEdsgHUDPdc87TlSeoNWY1KRojO0jKAC7Yy3ucADP0FGg1vqOrE1HxRY6ZevazRXDSJjJRVI5Ge5rRsLP7DA0CyboQ7GJcY8tCc7PoCSBgDC4HbJztR8L2Op3r3U0twsj4yEZQOBjuKa5b6mtL2fN7+xV/4TfTf+eF3/AN8L/wDFUf8ACb6b/wA8Lv8A74X/AOKo/wCEI03/AJ73f/fa/wDxNH/CEab/AM97v/vtf/iar3Do/wBk8w/4TfTf+eF3/wB8L/8AFVPaeLbC8n8qOG8BxniEv+iZP6VyviPSrLSLiGC2kmeRlLP5jA4HboB71seCLHCT37Dlv3SfTqf6flTcY8ty6lGiqXtFc6i2vIrvd5azrtxnzYHj6+m4DP4Vi+M9euvDujRXlpHC8jTrGRMCRgqx7Ec8CuirE8U+Hv8AhJdLjsvtX2bZMJd/l784BGMZHrU0+XnXNseRiVUdKSpfF0MPwdrN14nN/dTR29rdQlNslurAPkH/AFgLfOOMc9ATgg812Fu1ydyXMaBlxiSNsq49cHlTx05xkcnmsPwn4U/4ReO6X7b9p+0FTnytm3Gfc5610dOq4ub5NgwjrKhGNf4v+CFFFFZm4UUUUAZ+u38ul6Bf38Co0tvA8qBwSpIGRnGOK878K/FC+1XW1ttWXTra08qSRpEVlI2qW7sfQ9q7rxf/AMibrP8A15y/+gmvm+0t57y6itLdS0s7rGqg/eJIwPzxWVSTTVj6fJMBQxWFqe1Wt9+2h6Pr3xevZbh4tDt44YAcCaZdzt7gdB+Oaw4vih4rjlDvfxyr/ce3QD9AD+tet+GPBel+G7GNUt45r3AMty6gsW77c9B7CtXU9F03WbZoNQs4Z0YYyy/MvuD1B+lHLJ63JWZZZRl7OGH5o93a/rqv1RyXhH4l2mvOLPUIvst+fuiMFkl/3RyQfbn612f26L+5cf8AgPJ/8TXzz4r0Cbwj4ka2jlfYMTW02cNtzwcjuCCPwr3Twlrf/CQeGbPUGx5zLtmA/vrwfzxn8alObdr/AIf8EwzjLqVKEMVhv4cvw/r8DS+3Rf3Lj/wHk/8Aia86n+I2rR63JZpbWXlLcmIFo3Dbd2Ofm649q9Or591olfEGoEEgi6kII7fOa0ipL4n/AF95wYClGo5Kauek+JviFFpdw9lpkaXFwhw8jn5EPpx1Ncc/xB8SM+4XyKP7ogTH6jNdr4P8F2dlp8N9qECT3syh9sgyIgeQMHv6muwktoJYjFJDG8Z4KMgI/KrH7XD0nyqHN5s850H4lytcpb6zHH5bHH2iMYK+7DuPpXpQIYAggg8gjvXjnj7w9BoeqxS2ibLW6UsqDojDqB7cg/jXe+AL97/wnbiRtz27NAT7DkfoRQLFUqbpqtT0TOnqK4uIrSBp522RJjc2CQozjJ9AO56AZJwBUtFC8zgCkJCgknAHJJpI444YkiiRUjRQqoowFA6ADsKx/FF99i0SUKcSTful/Hr+maaV3ZFQi5yUV1OE1S7bU9WmnUE+Y+EHt0ArvdNM+n6dBarpV2fLXBIaLk9z9/1zXIeFLH7ZrSOwzHbjzD9e368/hXo9a1HbQ7sbNK1NdCDzpmgWRbZlfPzRSOAwHtjIJ/Hv1Fc94u8T3Gg6THcWsCC5aYRmO5QkbSGORtOD0HQnGea6iuJ+KP8AyK8H/X4n/oD0UVGU0mjwsc6kKMpwlayLXgjxPe+JY71ryK3jMBQL5KsM5znOSfSusrzP4WxNJBqjRytG6tHgjkHhuCO4/I+4r0eHzxuE/lnHR0yN34Hp+Z/CniIKNRqJGX1p1KEXO7bvr82S0UUVgegFFFFAGL4v/wCRN1n/AK85f/QTXi3w0tluPHlhvGRGJJMe4Q4/XFe0+L/+RN1n/rzl/wDQTXifw5vEs/HWnNIQFlLRZPqykD9cVjP4kfVZMpPLcRy72f8A6SfQ1FFFbHyp5X8aLZTb6TdAfOGkjJ9QQpH8j+dXfg3Oz+Hb6AniO63D8VH+FZ3xnvE/4lNkCC48yVh6DgD/ANm/KtP4O2zR+Gbu4YYE10QvuFVefzJ/Ksf+Xh9VU0yGPN30/wDAmdnqHh7RdWnWfUtH0+8mVdgkubZJGC5JxlgTjJPHvXiN5bwp4kuLaONI4Vu2jVEXCqu/AAA6DFfQFeCXv/I3XP8A1/t/6MNankZc3eXoe99KKKKZ5h578VQPsOmnuJXH6Cp/hl5h8NXixOqt9rOCy7gPlXtkfzqH4q/8g/Tv+ur/AMhVj4W/8i/d/wDX0f8A0BaD0n/uS9f1Ov8APu0/1lluz08iUNj67tv6Zo/tG0H+sl8n089THn6bgM/hVqinddjzArgPGV99o1VbZTlLdcH/AHjyf6V2spttMsZpkiSKKNS5VFCgnHt3rzGCOXVtVVCcy3EuWPpk5JrSmtbnfgYe86j6HXeHNDil0ENcNcIZ5PMzBcSQtgZABZGBI5JxnHI9K0/7Fu1+WLxFqscY4VMQPtHYbniLH6sST3JNakUaQxJEgwiKFUegFPrKWruc060pScihZQanDMRd39vc24XCAWpjlJ4wWYOVJxnOEUZPGBxXMfFH/kV4P+vxP/QHrsZxPsBtzGHByRIDhh6ZHT6849DXDfEuW5bw3AlxbBP9LUh45A6fdfjkA5/DHvWuH0qxRw5inLCzlpsVvhP/AKjVf96L+TV6PXmnwruYIU1GOWeON5HiCKzgFj83Qd69LqsT/FZjlaawkPn+bCiiisDvCiiigDF8X/8AIm6z/wBecv8A6Ca+b7VbjzfNtg/mQjzdydVC87vwr6K8a20c/hLVJHaUNFaSlQkzID8vcAgN075rx34a2kV74xit595jeGQMEkZCRt6ZUg4rGok5JH12Q1nRwNera/Lr66HpHhj4maRqllHHqlzHZX6gCTzfljc/3g3QfQ/rWrqfj3w3pls0p1SC5YD5YrVxIzH044H4kVy2ufB+1uZmm0a8+yg/8sJgXQfRuo/HNYSfBzXDKokv9OWPPLKzkgfTaP507zWljmWGyetL2vtXFfy/pt/mctq+pah4z8TmZYi09y4jggU52r2UfzJ+pr6A8O6OmgaBZ6ahDGFPnYfxOeWP5k1l+FPAumeFgZoy1zesMNcSDBA9FH8I/X3rqKcItavc5s3zKniFGhh1anH8QrwPUAW8WXQDFSb5xuHUfOfWvfK4Kf4a+dq8l/8A2tjfOZtn2bpls4zurQ4MFWhScud2udP52u2fM1ta6jH1LWpMEnpgRuSp9cmReCeMjnWoopJWONu5598Vf+Qfp3/XV/5CrHwt/wCRfu/+vo/+gLWz4q8Mf8JNb20X2z7N5Lls+VvzkY9RT/C3hz/hGtPmtftX2nzJTJu8vZjgDGMn0pnY60Pqvs76/wDBN2iio/Pj+0/Z92Jdm8KQRlc4JHrjjOOmRnqKDiOb8a33k6fFZqfmnbLf7o/+vj8qx/C2kQ37XE1zbtNEgCpg4Kv13A5BDDggjkHBGDW9rHhd9Xvzctf+WNoVU8rO0D33eua1NJ01NJ09LVH3kElnxjcT3x/npWvPyx916na6sI4fkg9XuUl0SBG/0LVNVtJjxua7eYkem2fev4gZ464yDJ9g1uD5bbW4pUPJa+shI+fQGJoxj22k9eegGsyq67WAIPYikSNUztGAew6flS9tU62fqk/zucN31Kti2pHzF1CK1XbgJJbysfM65JQqNnY43N1xnjJ5X4o/8ivB/wBfif8AoD121Yninw9/wkulx2X2r7NsmEu/y9+cAjGMj1qqc0qik9Ec+MpyqUJQgtWjkvhUiyWuro6hkYxhlYZBGG4Nd/Fp9rbyh4IvJx/BExRD7lQdpPuR6elYvhPwp/wi8d0v237T9oKnPlbNuM+5z1ro6WIcZ1HJCy+FSjho05aPW/3sKhurW3vbd7e7gingfG6OVAytg5GQeOoBqais02ndHUZP2DUdP5027+0Q/wDPrfyM2P8Adm5cckk7g+eANoorWorT2t/iSf8AXlYnl7MxfF//ACJus/8AXnL/AOgmvHvhV/yPNv8A9cZP/Qa9u1jT/wC1dGvNP83yvtMLReZt3bcjGcZGa47wr8Nf+EZ12PU/7W+07EZfL+zbM5GOu4/yrmlFuSZ9Bl+NoUcBWozlaUr2Vn2O+ooorQ8EKKKKACiobpbh7d1tJYopzja8sZkUc85UMpPGe4rO+0a/D9/TrC4RPvPDeMjyAd1Ro8AnspfHYt3oGlc0btp0s52tUV7gRsYkbozY4B5Hem/bbc2KXvmf6M6K4k2nG04wT6DnJJ6Dk4xWBY69NY3lzZ6np2qQhpGntmeMXDtGxBKkRM5+Viw4GFXywSCwztaRG8OlQW7oym3Bg+YY3BCUDY/2goP49+tKSalYvlSjr3LtFZ/kyab88G+S0HW3AyYh6x4GSB/d54+7jAU6FCdyZRttsFV7i186a3mR9ksL5DYzuU8Mp9j1+qqecYqxRTJauFFFFABTSwDhO5BP5Y/xp1JgZzjn1pO/QBaKKKYBRRRQAUUU2SRIo2kkdURQWZmOAAOpJoAdRVe2vrS93fZbqCfZjd5UgbbnpnH0NFNprRiTTV0WKKKKQwooooAKKKKACiiigDJ1z9wLG/j4nhu4Ygf7ySyLE6nuRhg2P7yITnGK1qKKp7Ip7IKKKKkkK5ebWr2y8d2eh+Ys1rdxNOXlUb4+HwqlcDaNg6gnk80UVcFozswsYyjUutkdRRRRUHGFZ91eS2+s2FspBiuRIGBH3dq5BH1zznPTtRRWVZtJW7ozqNpK3dGhRRRWpoFFFFABRRRQBXubG0vdv2q1gn2Z2+bGG2564z9BRRRVKclomQ6cG7tH/9k=","msg":"成功","code":"000000"}
```
EXT error
```
Cannot invoke "String.length()" because "this.data" is null
```

**Comment by f0ng** [comment]
> POST
> 
> ```
> POST /portal/user/getCaptcha HTTP/1.1
> Host: xx.xx.xx.xx
> Content-Length: 0
> ChildAuthorization: 
> Accept: application/json, text/plain, */*
> X-Requested-With: XMLHttpRequest
> Accept-Language: zh-CN
> Authorization: 
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.5481.178 Safari/537.36
> Content-Type: application/x-www-form-urlencoded; charset=UTF-8
> Accept-Encoding: gzip, deflate
> Connection: close
> ```
> 
> resp
> 
> ```
> HTTP/1.1 200 OK
> Server: nginx
> Date: Tue, 11 Apr 2023 04:10:12 GMT
> Content-Type: application/json;charset=UTF-8
> Content-Length: 6785
> Connection: close
> Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Credentials: true
> Access-Control-Allow-Methods: GET,POST,OPTIONS,PUT,DELETE
> Access-Control-Allow-Headers: Content-Type,Content-Length,Accept-Encoding,X-Requested-with, Origin
> 
> {"data":"data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCABkAMgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3+iiigAoqKK5gmeRIpo5HjOHVGBKn0Pp0NS0AUtQl1GDy5bG3huUXPnQM+yRhwco33S3BG1sAlh8645fYXy38DSCC5gZG2PHcRFGVgBkc8MOfvKSp7E1aopiGSypDGZJDtQdTjp7n29+1OR1kRXRgysMhgcgj1paqvZhHaW1YQSsctwSjE9SygjJ9+DwOccVLuTJyTuldFqq9/a/bbGa28x4y68OkjoVPUHKMrYz1AIyOO9NS7ZHWO6hMLMcBgd0bH03Y47D5gMk4GatUaMcJp6xZyn/CPXcHDpc3SryZItdvIncf7MbOQD2GXwfUZ4Psemx8XUHie3fqE+23k2R65ikdfwJz7dM9XVS906C/2ec90uzOPIupYc5x12MM9O9Z+ztsbxq1L6zf9fMXT7iyuLRfsF3HcwxYj3pP5vIA4LZJJxjqc81arJ/4R2y/576n/wCDS5/+OVbstOgsN/kvdNvxnz7qWbGM9N7HHXtWiv1FJQtdNt+n/BLdFFFMzCiis270K0vLl7iWbUFd8ZEOo3ES8DHCo4UdOwqoqLfvO34/qgNKisb/AIRiw/5+NW/8G91/8cqS0s5tFSRYmnu7RnLnzp5JZo8+hctuHsMYA6MTzUlTt7rd/T/gscU2atFMhmjuIllibcp9sEHoQQeQQeCD0p9ZiatowooooAr3KXb7fss8EWM7vNhMmfTGGXHf1oqxRVKTQrBRRRUjIbiztrrb9ot4ZtudvmIGxn0zUP8AZdqOIxNEvZIZ3jUfRVIA/KrlRXCyNEBFnd5iE4OONwz+maTBuyIPsl0nzR6lMzDoJo0ZfxChT+oqxEXVFSaSN5cEkou0HnsCT6jvUlMaMM6PkhkJxjvkdD7d/wABQ79AH0UUUwKU+mQyzNcRNJa3LY3TwEKzcY+YEFX44G4HGeMVH9qv7Ti6tPtKDnz7QdB3LRsdwx2ClycHgcCtGincViG1u7e8jMlvKsiqdrAdUburDqrDPIPIqO/vPsMCztHuhDqJWzjy0Jxv+gJBOSMLk9sFLrTre6kExDRXKjatxEdsgHUDPdc87TlSeoNWY1KRojO0jKAC7Yy3ucADP0FGg1vqOrE1HxRY6ZevazRXDSJjJRVI5Ge5rRsLP7DA0CyboQ7GJcY8tCc7PoCSBgDC4HbJztR8L2Op3r3U0twsj4yEZQOBjuKa5b6mtL2fN7+xV/4TfTf+eF3/AN8L/wDFUf8ACb6b/wA8Lv8A74X/AOKo/wCEI03/AJ73f/fa/wDxNH/CEab/AM97v/vtf/iar3Do/wBk8w/4TfTf+eF3/wB8L/8AFVPaeLbC8n8qOG8BxniEv+iZP6VyviPSrLSLiGC2kmeRlLP5jA4HboB71seCLHCT37Dlv3SfTqf6flTcY8ty6lGiqXtFc6i2vIrvd5azrtxnzYHj6+m4DP4Vi+M9euvDujRXlpHC8jTrGRMCRgqx7Ec8CuirE8U+Hv8AhJdLjsvtX2bZMJd/l784BGMZHrU0+XnXNseRiVUdKSpfF0MPwdrN14nN/dTR29rdQlNslurAPkH/AFgLfOOMc9ATgg812Fu1ydyXMaBlxiSNsq49cHlTx05xkcnmsPwn4U/4ReO6X7b9p+0FTnytm3Gfc5610dOq4ub5NgwjrKhGNf4v+CFFFFZm4UUUUAZ+u38ul6Bf38Co0tvA8qBwSpIGRnGOK878K/FC+1XW1ttWXTra08qSRpEVlI2qW7sfQ9q7rxf/AMibrP8A15y/+gmvm+0t57y6itLdS0s7rGqg/eJIwPzxWVSTTVj6fJMBQxWFqe1Wt9+2h6Pr3xevZbh4tDt44YAcCaZdzt7gdB+Oaw4vih4rjlDvfxyr/ce3QD9AD+tet+GPBel+G7GNUt45r3AMty6gsW77c9B7CtXU9F03WbZoNQs4Z0YYyy/MvuD1B+lHLJ63JWZZZRl7OGH5o93a/rqv1RyXhH4l2mvOLPUIvst+fuiMFkl/3RyQfbn612f26L+5cf8AgPJ/8TXzz4r0Cbwj4ka2jlfYMTW02cNtzwcjuCCPwr3Twlrf/CQeGbPUGx5zLtmA/vrwfzxn8alObdr/AIf8EwzjLqVKEMVhv4cvw/r8DS+3Rf3Lj/wHk/8Aia86n+I2rR63JZpbWXlLcmIFo3Dbd2Ofm649q9Or591olfEGoEEgi6kII7fOa0ipL4n/AF95wYClGo5Kauek+JviFFpdw9lpkaXFwhw8jn5EPpx1Ncc/xB8SM+4XyKP7ogTH6jNdr4P8F2dlp8N9qECT3syh9sgyIgeQMHv6muwktoJYjFJDG8Z4KMgI/KrH7XD0nyqHN5s850H4lytcpb6zHH5bHH2iMYK+7DuPpXpQIYAggg8gjvXjnj7w9BoeqxS2ibLW6UsqDojDqB7cg/jXe+AL97/wnbiRtz27NAT7DkfoRQLFUqbpqtT0TOnqK4uIrSBp522RJjc2CQozjJ9AO56AZJwBUtFC8zgCkJCgknAHJJpI444YkiiRUjRQqoowFA6ADsKx/FF99i0SUKcSTful/Hr+maaV3ZFQi5yUV1OE1S7bU9WmnUE+Y+EHt0ArvdNM+n6dBarpV2fLXBIaLk9z9/1zXIeFLH7ZrSOwzHbjzD9e368/hXo9a1HbQ7sbNK1NdCDzpmgWRbZlfPzRSOAwHtjIJ/Hv1Fc94u8T3Gg6THcWsCC5aYRmO5QkbSGORtOD0HQnGea6iuJ+KP8AyK8H/X4n/oD0UVGU0mjwsc6kKMpwlayLXgjxPe+JY71ryK3jMBQL5KsM5znOSfSusrzP4WxNJBqjRytG6tHgjkHhuCO4/I+4r0eHzxuE/lnHR0yN34Hp+Z/CniIKNRqJGX1p1KEXO7bvr82S0UUVgegFFFFAGL4v/wCRN1n/AK85f/QTXi3w0tluPHlhvGRGJJMe4Q4/XFe0+L/+RN1n/rzl/wDQTXifw5vEs/HWnNIQFlLRZPqykD9cVjP4kfVZMpPLcRy72f8A6SfQ1FFFbHyp5X8aLZTb6TdAfOGkjJ9QQpH8j+dXfg3Oz+Hb6AniO63D8VH+FZ3xnvE/4lNkCC48yVh6DgD/ANm/KtP4O2zR+Gbu4YYE10QvuFVefzJ/Ksf+Xh9VU0yGPN30/wDAmdnqHh7RdWnWfUtH0+8mVdgkubZJGC5JxlgTjJPHvXiN5bwp4kuLaONI4Vu2jVEXCqu/AAA6DFfQFeCXv/I3XP8A1/t/6MNankZc3eXoe99KKKKZ5h578VQPsOmnuJXH6Cp/hl5h8NXixOqt9rOCy7gPlXtkfzqH4q/8g/Tv+ur/AMhVj4W/8i/d/wDX0f8A0BaD0n/uS9f1Ov8APu0/1lluz08iUNj67tv6Zo/tG0H+sl8n089THn6bgM/hVqinddjzArgPGV99o1VbZTlLdcH/AHjyf6V2spttMsZpkiSKKNS5VFCgnHt3rzGCOXVtVVCcy3EuWPpk5JrSmtbnfgYe86j6HXeHNDil0ENcNcIZ5PMzBcSQtgZABZGBI5JxnHI9K0/7Fu1+WLxFqscY4VMQPtHYbniLH6sST3JNakUaQxJEgwiKFUegFPrKWruc060pScihZQanDMRd39vc24XCAWpjlJ4wWYOVJxnOEUZPGBxXMfFH/kV4P+vxP/QHrsZxPsBtzGHByRIDhh6ZHT6849DXDfEuW5bw3AlxbBP9LUh45A6fdfjkA5/DHvWuH0qxRw5inLCzlpsVvhP/AKjVf96L+TV6PXmnwruYIU1GOWeON5HiCKzgFj83Qd69LqsT/FZjlaawkPn+bCiiisDvCiiigDF8X/8AIm6z/wBecv8A6Ca+b7VbjzfNtg/mQjzdydVC87vwr6K8a20c/hLVJHaUNFaSlQkzID8vcAgN075rx34a2kV74xit595jeGQMEkZCRt6ZUg4rGok5JH12Q1nRwNera/Lr66HpHhj4maRqllHHqlzHZX6gCTzfljc/3g3QfQ/rWrqfj3w3pls0p1SC5YD5YrVxIzH044H4kVy2ufB+1uZmm0a8+yg/8sJgXQfRuo/HNYSfBzXDKokv9OWPPLKzkgfTaP507zWljmWGyetL2vtXFfy/pt/mctq+pah4z8TmZYi09y4jggU52r2UfzJ+pr6A8O6OmgaBZ6ahDGFPnYfxOeWP5k1l+FPAumeFgZoy1zesMNcSDBA9FH8I/X3rqKcItavc5s3zKniFGhh1anH8QrwPUAW8WXQDFSb5xuHUfOfWvfK4Kf4a+dq8l/8A2tjfOZtn2bpls4zurQ4MFWhScud2udP52u2fM1ta6jH1LWpMEnpgRuSp9cmReCeMjnWoopJWONu5598Vf+Qfp3/XV/5CrHwt/wCRfu/+vo/+gLWz4q8Mf8JNb20X2z7N5Lls+VvzkY9RT/C3hz/hGtPmtftX2nzJTJu8vZjgDGMn0pnY60Pqvs76/wDBN2iio/Pj+0/Z92Jdm8KQRlc4JHrjjOOmRnqKDiOb8a33k6fFZqfmnbLf7o/+vj8qx/C2kQ37XE1zbtNEgCpg4Kv13A5BDDggjkHBGDW9rHhd9Xvzctf+WNoVU8rO0D33eua1NJ01NJ09LVH3kElnxjcT3x/npWvPyx916na6sI4fkg9XuUl0SBG/0LVNVtJjxua7eYkem2fev4gZ464yDJ9g1uD5bbW4pUPJa+shI+fQGJoxj22k9eegGsyq67WAIPYikSNUztGAew6flS9tU62fqk/zucN31Kti2pHzF1CK1XbgJJbysfM65JQqNnY43N1xnjJ5X4o/8ivB/wBfif8AoD121Yninw9/wkulx2X2r7NsmEu/y9+cAjGMj1qqc0qik9Ec+MpyqUJQgtWjkvhUiyWuro6hkYxhlYZBGG4Nd/Fp9rbyh4IvJx/BExRD7lQdpPuR6elYvhPwp/wi8d0v237T9oKnPlbNuM+5z1ro6WIcZ1HJCy+FSjho05aPW/3sKhurW3vbd7e7gingfG6OVAytg5GQeOoBqais02ndHUZP2DUdP5027+0Q/wDPrfyM2P8Adm5cckk7g+eANoorWorT2t/iSf8AXlYnl7MxfF//ACJus/8AXnL/AOgmvHvhV/yPNv8A9cZP/Qa9u1jT/wC1dGvNP83yvtMLReZt3bcjGcZGa47wr8Nf+EZ12PU/7W+07EZfL+zbM5GOu4/yrmlFuSZ9Bl+NoUcBWozlaUr2Vn2O+ooorQ8EKKKKACiobpbh7d1tJYopzja8sZkUc85UMpPGe4rO+0a/D9/TrC4RPvPDeMjyAd1Ro8AnspfHYt3oGlc0btp0s52tUV7gRsYkbozY4B5Hem/bbc2KXvmf6M6K4k2nG04wT6DnJJ6Dk4xWBY69NY3lzZ6np2qQhpGntmeMXDtGxBKkRM5+Viw4GFXywSCwztaRG8OlQW7oym3Bg+YY3BCUDY/2goP49+tKSalYvlSjr3LtFZ/kyab88G+S0HW3AyYh6x4GSB/d54+7jAU6FCdyZRttsFV7i186a3mR9ksL5DYzuU8Mp9j1+qqecYqxRTJauFFFFABTSwDhO5BP5Y/xp1JgZzjn1pO/QBaKKKYBRRRQAUUU2SRIo2kkdURQWZmOAAOpJoAdRVe2vrS93fZbqCfZjd5UgbbnpnH0NFNprRiTTV0WKKKKQwooooAKKKKACiiigDJ1z9wLG/j4nhu4Ygf7ySyLE6nuRhg2P7yITnGK1qKKp7Ip7IKKKKkkK5ebWr2y8d2eh+Ys1rdxNOXlUb4+HwqlcDaNg6gnk80UVcFozswsYyjUutkdRRRRUHGFZ91eS2+s2FspBiuRIGBH3dq5BH1zznPTtRRWVZtJW7ozqNpK3dGhRRRWpoFFFFABRRRQBXubG0vdv2q1gn2Z2+bGG2564z9BRRRVKclomQ6cG7tH/9k=","msg":"成功","code":"000000"}
> ```
> 
> EXT error
> 
> ```
> Cannot invoke "String.length()" because "this.data" is null
> ```

是什么问题，按道理有响应的话没什么问题的

**Comment by passwa11** [comment]
并不是 在插件里 点了 获取后 没有响应 插件会报错
`Cannot invoke "String.length()" because "this.data" is null`

**Comment by f0ng** [comment]
试着把请求头里空的参数删了



发自iPhone


------------------ 原始邮件 ------------------
发件人: passwa11 ***@***.***&gt;
发送时间: 2023年4月12日 18:02
收件人: f0ng/captcha-killer-modified ***@***.***&gt;
抄送: f0ng ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [f0ng/captcha-killer-modified] 【BUG】 点击获取无反应 (Issue #23)

**Comment by passwa11** [comment]
maybe the Authorization:  null cause this

**Comment by f0ng** [comment]
`0.23-beta5`修复该问题
