### ISSUE TITLE
大佬那种分开两个数据包获取验证码的有办法解决吗

### ISSUE THREAD

**Issue by fengzirock** [f0ng/captcha-killer-modified#28]
第一个包
![image](https://github.com/f0ng/captcha-killer-modified/assets/59859409/cf223f58-ef2e-4e2c-a056-182697c75316)
第二个包
![image](https://github.com/f0ng/captcha-killer-modified/assets/59859409/8f7cf286-d313-4139-9eec-0621a50166bc)

**Comment by f0ng** [comment]
可以，参考https://github.com/f0ng/captcha-killer-modified/blob/main/FAQ.md#6-%E9%AA%8C%E8%AF%81%E7%A0%81%E8%BF%9B%E8%A1%8C%E4%BA%8C%E6%AC%A1%E5%A4%84%E7%90%86%E7%9A%84%E6%A1%88%E4%BE%8B%E9%AA%8C%E8%AF%81%E7%A0%81%E4%B8%BAgif%E5%9B%BE%E4%B8%94%E9%AA%8C%E8%AF%81%E7%A0%81%E5%85%B7%E4%BD%93%E6%98%AF%E5%9C%A8gif%E5%9B%BE%E7%9A%84%E7%AC%AC%E4%BA%8C%E5%B8%A7%E6%97%A0%E6%B3%95%E7%9B%B4%E6%8E%A5%E8%AF%86%E5%88%AB
本地把你这两个包的流程弄成一个接口实现就行

**Comment by fengzirock** [comment]
好滴感谢

**Comment by shannaburns** [comment]
> 好滴感谢

师傅，能参考一下你的二开脚本不，我也遇到跟你一样的问题
