### ISSUE TITLE
建议在验证码返回包中加一个自定义标记验证码位置的功能

### ISSUE THREAD

**Issue by xxnbyy** [f0ng/captcha-killer-modified#3]
RT
比如这种验证码就无法被识别，很难受，可以参考intruder里那种标记功能，自己标记验证码位置。
![image](https://user-images.githubusercontent.com/20261647/159642351-4321ca13-cc11-4640-836f-e46e527435f8.png)

**Comment by f0ng** [comment]
感谢师傅反馈，这个问题最近也在思考当中，预计下版本更新

**Comment by f0ng** [comment]
`0.14`版本已经优化该问题
