### ISSUE TITLE
intruder 無法串接起來，持續出現 Interface URL format Invalid

### ISSUE THREAD

**Issue by cjiso1117** [f0ng/captcha-killer-modified#30]
burp版本：v2023.6.1
启动burp的jdk版本：openjdk 17.0.7 2023-04-18
burp的Extender中Options配置的jdk版本：未設置

intruder 配置
Pitchfork
![image](https://github.com/f0ng/captcha-killer-modified/assets/65863383/ad70f7bf-b093-457b-af4c-d9399172af8c)
payload 1
![image](https://github.com/f0ng/captcha-killer-modified/assets/65863383/34078657-e99b-407a-9e6c-71572dae662b)
payload 2
![image](https://github.com/f0ng/captcha-killer-modified/assets/65863383/9825604f-f35d-4fbf-9d16-9a8e365c07c7)
resource pool
![image](https://github.com/f0ng/captcha-killer-modified/assets/65863383/45ef488d-f66b-4229-9b3d-bb11f6b8a720)
結果
![image](https://github.com/f0ng/captcha-killer-modified/assets/65863383/736c14b0-b51a-4683-af06-99b0c35fcfbb)

panel 設置是對的，可以跑起來
![image](https://github.com/f0ng/captcha-killer-modified/assets/65863383/2dab4ea2-4927-4acc-b63a-44528dbe6eec)

**Comment by f0ng** [comment]
应该是获取验证码的时候变成了`http://null`了，验证码获取的问题，这个是未知bug
