### ISSUE TITLE
插件 报错 

### ISSUE THREAD

**Issue by cqrlhz** [f0ng/captcha-killer-modified#34]
![image](https://github.com/f0ng/captcha-killer-modified/assets/63200706/eb261033-a30c-4171-a5d2-46479d3010a9)

**Comment by cqrlhz** [comment]
导致固定验证码
![image](https://github.com/f0ng/captcha-killer-modified/assets/63200706/99c5e58b-de94-40d9-ab8b-98f717af469d)

**Comment by f0ng** [comment]
导致接口为null的问题未知，可能是线程大了的问题
