### ISSUE TITLE
mac系统报错（已解决）

### ISSUE THREAD

**Issue by wanzhoukaoyu** [f0ng/captcha-killer-modified#36]
<img width="998" alt="image" src="https://github.com/f0ng/captcha-killer-modified/assets/22409317/2fa2cae0-bdd1-4268-9282-ef4aad3a1e1b">
<img width="756" alt="image" src="https://github.com/f0ng/captcha-killer-modified/assets/22409317/dde8a2bf-acb7-46e3-b647-3967f014e44c">

**Comment by f0ng** [comment]
参考faq，应该是PIL库的问题
