### ISSUE TITLE
@captcha-killer-modified@关键字在请求时无法转化为实际值

### ISSUE THREAD

**Issue by sddzcuigc** [f0ng/captcha-killer-modified#39]
@captcha-killer-modified@关键字提取了 token，但是请求时无法转化还是原始请求token：''@captcha-killer-modified@''

**Comment by f0ng** [comment]
选中使用插件按钮



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yang xiaoyu ***@***.***&gt;
发送时间: 2023年9月26日 18:41
收件人: f0ng/captcha-killer-modified ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [f0ng/captcha-killer-modified] @captcha-killer-modified@关键字在请求时无法转化为实际值 (Issue #39)

**Comment by sddzcuigc** [comment]
选了

**Comment by sddzcuigc** [comment]
![Uploading Screenshot_20230926_184209.jpg…]()

**Comment by sddzcuigc** [comment]
不选连验证码都不更新

**Comment by sddzcuigc** [comment]
![Screenshot_20230926_184209](https://github.com/f0ng/captcha-killer-modified/assets/85976753/1e74bdf4-a8ed-4e41-b01d-ef70bd984122)

**Comment by f0ng** [comment]
关键字提取写了吗？还有就是logger模块看真实请求



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Yang xiaoyu ***@***.***&gt;
发送时间: 2023年9月26日 18:44
收件人: f0ng/captcha-killer-modified ***@***.***&gt;
抄送: f0ng ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [f0ng/captcha-killer-modified] @captcha-killer-modified@关键字在请求时无法转化为实际值 (Issue #39)

**Comment by sddzcuigc** [comment]
你是说点开intruder之后不是真实请求吗
![Screenshot_20230926_185555](https://github.com/f0ng/captcha-killer-modified/assets/85976753/7ce4f734-46e1-47b6-a560-b9953ee27695)

**Comment by sddzcuigc** [comment]
那没问题了

> 关键字提取写了吗？还有就是logger模块看真实请求 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Yang xiaoyu ***@***.***&gt; 发送时间: 2023年9月26日 18:44 收件人: f0ng/captcha-killer-modified ***@***.***&gt; 抄送: f0ng ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [f0ng/captcha-killer-modified] @captcha-killer-modified@关键字在请求时无法转化为实际值 (Issue #39) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
