### ISSUE TITLE
python脚本报错

### ISSUE THREAD

**Issue by ekko-zhao** [f0ng/captcha-killer-modified#4]
师傅，我运行脚本，然后在Burp端调用的时候，错误信息如下：
![image](https://user-images.githubusercontent.com/26781518/160375424-bb0a448e-3326-419e-87e4-69f38d2f0d67.png)
burp端配置如下：
![image](https://user-images.githubusercontent.com/26781518/160375671-766149f4-5a5a-4ac0-b2d7-41900b699379.png)
谢谢师傅。

**Comment by ekko-zhao** [comment]
已解决，修改代码如下：
![image](https://user-images.githubusercontent.com/26781518/160378142-556da3cf-c556-4550-92d9-1ccf74d181d0.png)

**Comment by f0ng** [comment]
感谢师傅反馈，可能与python版本有关

**Comment by LSForever** [comment]
3.8.13的python也报这个错了
![image](https://user-images.githubusercontent.com/58731947/185053452-155e0b7c-19b5-4093-adbc-e1bd4d66464f.png)
按照 @ekko-zhao 师傅的方法解决了
