### ISSUE TITLE
保存接口URL

### ISSUE THREAD

**Issue by zhiao6** [f0ng/captcha-killer-modified#41]
能不能加个记忆接口URL的功能，在公网vps使用的时候，每次使用都要重新输入，感觉有点麻烦

**Comment by f0ng** [comment]
<img width="603" alt="image" src="https://github.com/f0ng/captcha-killer-modified/assets/48286013/ce927a72-fd2f-4395-b71c-ecbd34717cbc">

保存模板即可

**Comment by zhiao6** [comment]
okkk
