### ISSUE TITLE
返回包400

### ISSUE THREAD

**Issue by zhiao6** [f0ng/captcha-killer-modified#42]
在burp中访问没问题
![image](https://github.com/f0ng/captcha-killer-modified/assets/74243945/b4625e79-5068-455b-b6c2-fc3b0562ae05)
但是在插件中就返回错误
![image](https://github.com/f0ng/captcha-killer-modified/assets/74243945/d2196731-d31f-44e3-acb5-9790f5a3a0be)

**Comment by f0ng** [comment]
换bp版本，原因未知



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhiao6 ***@***.***&gt;
发送时间: 2023年11月17日 15:13
收件人: f0ng/captcha-killer-modified ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [f0ng/captcha-killer-modified] 返回包400 (Issue #42)





 
在burp中访问没问题
 
 但是在插件中就返回错误

**Comment by uhhuhuhu** [comment]
> 在burp中访问没问题 ![image](https://github.com/f0ng/captcha-killer-modified/assets/74243945/b4625e79-5068-455b-b6c2-fc3b0562ae05) 但是在插件中就返回错误 ![image](https://github.com/f0ng/captcha-killer-modified/assets/74243945/d2196731-d31f-44e3-acb5-9790f5a3a0be)

把梯子关了
