### ISSUE TITLE
关于 验证码包发送到模块后少回车符的问题

### ISSUE THREAD

**Issue by fppecy** [f0ng/captcha-killer-modified#43]
验证码包发送到模块后少一个回车符号
点击发送后无响应，得手动添加
环境：Burp：2023.11.1.1 自带jre版本： 17.0.9
模块版本captcha-killer-modified-0.24.2-jdk14.jar
![image](https://github.com/f0ng/captcha-killer-modified/assets/44750501/09b5e97c-8b84-44aa-9a2f-d14ddb3251b9)

师傅可以解决一下嘛

**Comment by f0ng** [comment]
一般情况不会出现这个问题(正常get请求以两个\r\n截断)，根据站点不同可以手动添加

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fppecy ***@***.***&gt;
发送时间: 2023年11月28日 19:09
收件人: f0ng/captcha-killer-modified ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [f0ng/captcha-killer-modified] 关于 验证码包发送到模块后少回车符的问题 (Issue #43)

**Comment by fppecy** [comment]
师傅 我测试了一下，找了三四个站，所有验证码都会少一个回车。。。感觉是Burp版本太新了

**Comment by f0ng** [comment]
没啥问题
<img width="725" alt="image" src="https://github.com/f0ng/captcha-killer-modified/assets/48286013/86b35700-e1af-4852-8dd9-12d0b075af91">

**Comment by f0ng** [comment]
师傅方便的话加个v`f-f0ng`

**Comment by f0ng** [comment]
新版burp与未知版本的jdk或者是操作系统，会产生该问题，版本`0.24.3`修复该问题
