### ISSUE TITLE
识别验证码都是同一个

### ISSUE THREAD

**Issue by bingling123** [f0ng/captcha-killer-modified#45]
换了好几个版本都是这样，一直重复识别同一个验证码
![image](https://github.com/f0ng/captcha-killer-modified/assets/48980951/3c79e241-9b08-4ae0-899f-9ff1bac56c9f)

**Comment by f0ng** [comment]
参考 https://github.com/f0ng/captcha-killer-modified/blob/main/FAQ.md#14-intruder%E6%A8%A1%E5%9D%97%E9%83%BD%E6%98%AF%E4%B8%80%E4%B8%AA%E9%AA%8C%E8%AF%81%E7%A0%81
https://github.com/f0ng/captcha-killer-modified/blob/main/FAQ.md#16-%E8%8E%B7%E5%8F%96%E7%9A%84%E9%83%BD%E6%98%AF%E4%B8%80%E4%B8%AA%E9%AA%8C%E8%AF%81%E7%A0%81

**Comment by f0ng** [comment]
下载个最新的，你这个应该是旧版的

**Comment by f0ng** [comment]
还有就是，插件这个面板，不去手动获取验证码，识别的永远都是一个

**Comment by bingling123** [comment]
好的已经解决了，感谢！
