### ISSUE TITLE
请教如何多传递一个参数

### ISSUE THREAD

**Issue by zein9** [f0ng/captcha-killer-modified#46]
<img width="1270" alt="image" src="https://github.com/f0ng/captcha-killer-modified/assets/99779929/bab1594f-0b3d-46a2-8d30-12c515f1d1db">
如上图所示，get图形验证码的时候服务器除了给了一个图形，还给了一个vid参数，我在intruder爆破的时候也需要提供这个vid参数，每次get图形码的请求时候vid都会变，所以有没有办法从captcha-killer里把这个get请求时候response里的vid参数传递到intruder的payload里？谢谢！

**Comment by f0ng** [comment]
参考 https://github.com/f0ng/captcha-killer-modified/blob/main/FAQ.md#8-%E9%AA%8C%E8%AF%81%E7%A0%81%E4%B8%AD%E6%9C%89token%E7%AD%89%E6%A0%A1%E9%AA%8C%E5%8F%82%E6%95%B0%E8%BF%94%E5%9B%9E%E7%99%BB%E5%BD%95%E5%8C%85%E4%B8%AD%E6%9C%89%E6%A0%A1%E9%AA%8Ctoken%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E8%AE%BE%E7%BD%AE%E7%88%86%E7%A0%B4
