### ISSUE TITLE
你好 爆破时验证码都是测试时验证码没有按照每一个请求更新验证码是怎么回事呀

### ISSUE THREAD

**Issue by problemsname** [f0ng/captcha-killer-modified#48]
你好 爆破时验证码都是测试时验证码没有按照每一个请求更新验证码是怎么回事呀
![image](https://github.com/f0ng/captcha-killer-modified/assets/32014189/0dee1f3c-461d-43c6-8f71-b98191942f38)
![image](https://github.com/f0ng/captcha-killer-modified/assets/32014189/c94b3e42-3023-4ed9-a0eb-3585531e3203)

**Comment by problemsname** [comment]
已解决抱歉

**Comment by f0ng** [comment]
https://github.com/f0ng/captcha-killer-modified/blob/main/FAQ.md#14-intruder%E6%A8%A1%E5%9D%97%E9%83%BD%E6%98%AF%E4%B8%80%E4%B8%AA%E9%AA%8C%E8%AF%81%E7%A0%81
师傅参考这里
