### ISSUE TITLE
验证码问题

### ISSUE THREAD

**Issue by lo552441** [f0ng/captcha-killer-modified#5]
反馈一个问题

data:image类型的验证码。手动测试的时候可以获取验证码  也是识别出来

![屏幕截图 2022-03-29 234259](https://user-images.githubusercontent.com/88099858/160652358-8cd50caa-61f3-4886-a32d-b4c9370110a2.png)

一但放到Intruder里去跑就会识别不了验证码 报500错误
![屏幕截图 2022-03-29 234523](https://user-images.githubusercontent.com/88099858/160652612-1d9f2b57-74c7-476e-865d-d061b5bbe3ee.png)

![屏幕截图 2022-03-29 234626](https://user-images.githubusercontent.com/88099858/160652682-23078d2d-9861-4aa6-8d8b-ab4e7e3e587f.png)

codereg.py控制台那边报错：

![屏幕截图 2022-03-29 204445](https://user-images.githubusercontent.com/88099858/160652949-8a8ddf1a-13fa-461b-a853-fdc8df74b39a.png)

**Comment by lo552441** [comment]
补充一下：
其他图片类型的验证码跑起来正常，所以应该不是我参数设置的问题。
另外我的接口服务和burp不在一个机器，不确定是不是这个原因，如果是这个原因 手动获取为什么能正常识别到验证码内容。其他图片类型的验证码也能跑，所以应该可以排除这个问题。比较迷惑。。。

**Comment by f0ng** [comment]
感谢师傅反馈，晚点时间看看

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月29日(周二) 晚上11:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [f0ng/captcha-killer-modified] 验证码问题 (Issue #5)




 
补充一下：
 其他图片类型的验证码跑起来正常，所以应该不是我参数设置的问题。
 另外我的接口服务和burp不在一个机器，不确定是不是这个原因，如果是这个原因 手动获取为什么能正常识别到验证码内容。其他图片类型的验证码也能跑，所以应该可以排除这个问题。比较迷惑。。。

**Comment by f0ng** [comment]
师傅方便的话加个微信f-f0ng

**Comment by f0ng** [comment]
原因在于对`\r\n`以及`\/`没有适配，新版本`0.15`已经适配
