### ISSUE TITLE
DatatypeConverter.parseBase64Binary(str_img);无响应

### ISSUE THREAD

**Issue by liding58** [f0ng/captcha-killer-modified#51]
burp版本：2023-12
burp-JDK：openjdk18
burp插件-JDK：jdk8
源码版本：
<groupId>me.gv7.tools.burpext</groupId>
    <artifactId>captcha-killer-modified</artifactId>
    <version>0.17</version>
（不知道为什么clone下来的和release里差了那么多）

issue：
在Util.java的dataimgToimg(String str_img,String words) 方法的 byte[] img = DatatypeConverter.parseBase64Binary(str_img);
无报错无响应。
改为byte[] imageBytes = Base64.getDecoder().decode(str_img);后package可用。
直接用captcha-killer-modified-captcha-killer-modified-0.24.4-jdk8.jar没有这个问题

**Comment by f0ng** [comment]
用打包的就行，源码没更新

**Comment by liding58** [comment]
好的 👍
