### ISSUE TITLE
验证码的地址有随机的code校验，每次获取到的验证码地址唯一，这种验证码如何爆破

### ISSUE THREAD

**Issue by CJCniubi666** [f0ng/captcha-killer-modified#52]
![image](https://github.com/f0ng/captcha-killer-modified/assets/140289246/03439582-a229-49c2-8ba3-c5c8bcc8bb84)
![image](https://github.com/f0ng/captcha-killer-modified/assets/140289246/b6f443fb-127d-4356-b4d2-d8db8e3afe25)

**Comment by XingXiaoWu** [comment]
同问题。接口带时间戳，怎么填
