### ISSUE TITLE
【多请求了一次】

### ISSUE THREAD

**Issue by givemefivw** [f0ng/captcha-killer-modified#54]
之前项目也有这个issue
https://github.com/c0ny1/captcha-killer/issues/27
具体就是爆破的时候，插件在填入payload之后，会自动的多请求一次，导致插件页面的验证码实际上是填入payload的下一次请求
![image](https://github.com/f0ng/captcha-killer-modified/assets/65514141/71343932-70de-4c29-8bc5-581f57340e1b)

**Comment by f0ng** [comment]
这是正常的，因为显示的是下一次的，识别的是上一次的，当对上一个识别以后，马上就要获取下一个验证码，不然后续的爆破行为无法进行连贯

**Comment by givemefivw** [comment]
嗨呀，我刚才傻了师傅

**Comment by idsfsdf11** [comment]
![Image](https://github.com/user-attachments/assets/b9750f52-12a3-40cd-9c72-de79634adaba)
第一次识别的验证码被用力两次，导致后续的验证码跟payload都对应不上怎么办呀 求教

**Comment by handbye** [comment]
> ![Image](https://github.com/user-attachments/assets/b9750f52-12a3-40cd-9c72-de79634adaba) 第一次识别的验证码被用力两次，导致后续的验证码跟payload都对应不上怎么办呀 求教

我也遇到了这个问题，解决了吗
