### ISSUE TITLE
captcha-killer-modified  last

### ISSUE THREAD

**Issue by AngrySea412** [f0ng/captcha-killer-modified#58]
有一些乱码，不知道，怎么处理
![图片](https://github.com/user-attachments/assets/5cce0ad7-1835-4bd4-a725-fd3c22579668)

**Comment by f0ng** [comment]
验证码二进制数据包，正常的



发自我的iPhone


------------------ Original ------------------
From: DeepSea ***@***.***&gt;
Date: Tue,Sep 17,2024 6:53 PM
To: f0ng/captcha-killer-modified ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [f0ng/captcha-killer-modified] captcha-killer-modified  last (Issue#58)

**Comment by AngrySea412** [comment]
Ok ,谢谢，大神
