### ISSUE TITLE
不识别啊

### ISSUE THREAD

**Issue by gusechuisheng** [f0ng/captcha-killer-modified#6]
![image](https://user-images.githubusercontent.com/49669724/163363824-207b87b8-b5e8-43a0-a7e8-fa11d5dcd276.png)

**Comment by f0ng** [comment]
0.0.0.0改成127.0.0.1



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月14日(周四) 晚上6:09
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [f0ng/captcha-killer-modified] 不识别啊 (Issue #6)

**Comment by f0ng** [comment]
参考[FAQ.md-1](https://github.com/f0ng/captcha-killer-modified/blob/main/FAQ.md#1%E7%94%A8%E6%B3%95)

**Comment by gusechuisheng** [comment]
> 0.0.0.0改成127.0.0.1
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年4月14日(周四) 晚上6:09 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [f0ng/captcha-killer-modified] 不识别啊 (Issue #6) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

好滴
