### ISSUE TITLE
up你好，这种图片的相应包无法识别吗？

### ISSUE THREAD

**Issue by YingxueSec** [f0ng/captcha-killer-modified#60]
up你好，这种图片的相应包无法识别吗？有什么方法解决吗
<img width="1837" alt="image" src="https://github.com/user-attachments/assets/115dcdaf-1cfb-4d98-a876-082e22eeb101">

**Comment by f0ng** [comment]
看自己的代码运行是怎么报错，然后调试

**Comment by YingxueSec** [comment]
可以了，谢谢师傅
