### ISSUE TITLE
用不了@captcha-killer-modified@

### ISSUE THREAD

**Issue by Sh1tKing** [f0ng/captcha-killer-modified#64]
bp版本2023.10.2.1，captcha版本0.24.6，repeater和instruter都无法使用

**Comment by Sh1tKing** [comment]
![image](https://github.com/user-attachments/assets/cfc75e6b-7dfa-4bb4-800c-63010f4ac45e)
没有变色

**Comment by f0ng** [comment]
参考faq

**Comment by f0ng** [comment]
替换以后在logger里能看到实际的请求，这里关闭
