### ISSUE TITLE
插件无法暂停

### ISSUE THREAD

**Issue by 808Mak1r** [f0ng/captcha-killer-modified#7]
爆破关闭后，插件没有暂停还在不停的识别
只能靠重新启动bp，或者清空验证等数据体，但是在重新放入验证码的数据包，他又会自己调动识别

**Comment by f0ng** [comment]
没遇到过类似情况，师傅方便的话可以给我看下数据包

**Comment by f0ng** [comment]
该问题可能与`jdk`版本、`burp`版本有关
