### ISSUE TITLE
无法识别

### ISSUE THREAD

**Issue by jb2113286** [f0ng/captcha-killer-modified#8]
{"success":true,"message":"操作成功！","code":0,"result":"data:image/jpg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAAjAGkDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD3RIrlLwOu3yW4cNMzYwWI2jHBORnnoMAcA09kkNxHcRySeWVAaI8fQ8jIIzyOP0wXoXkdmMi7Ff5dnORjBDe+7PT0HvXJ/wDCyNJ/4WSfAxtb3+0cDE21PKz5Xmnndn7uO3X86AOpZZlukb7SoiZv9WyDLHaeAc9OM9CeDzjiophtnwZmRd3nszv8oVQAVGGBA6HkEc+9crrXxI0fQPGWm+EtQt7y4vr37OI5oo0MYeRyo3ZYEYIB4B6+1dLrek2Wt6fLp2o2kd1ZXKGGZWXJAOCCD2wQpyOhwcjbRcC6qvHLtAZo23MWZs7TxwO+Dkn26elRNcjzvvSIY874zEW3jsVx17dM4BwQD0+bvDfiC7+BnjfUdB16Ca+02VRIklvuB5GRJGrkKd2Ar+6cMdmDd8BaRefF/wCIVz4v8RQxvpVgUQWsiu8cjBTsjXPy4B/eOOhLfdw5wAfQc8svmIhYW8bkqJCy7t2eAAcjnHA9CehGDY2P54fzT5e0gx4GM5656+tUde1ZdB0K91aS2muYrOIzSxwFd+xeWI3EA4XJxnnGBzWJ4L8cad43spdS0qK6ithcG3dL3CNvCBvkClgcg8jcMYzjnJAOlvDttXbLLjB3I2COeuen58evGaUTsZkXyZPLdAVkx354I6jgd/p168X4V+JGmeMtVv49BtNSmtrN1+03EqII9p3BWjXfv+bbnG3op4DHnoPFPiez8I6Dd6zqEFzJa2yoWECBmO51TAyQM5YHkjjpnBoA05LcvuxPMjFw4KsPl4xgAjGPYg8nPXFKVW4dwwmXyyUyGZQ2VHIweeuM9iDXxjp2q6Brer6jqXj241+6urlldJtOMO4nkMGDjAGNoULgADGMYx9iEhw9zPdeTZsAQFmAVuSA27sCNhGCOp/EAvooRFUZwowMkk/metLUKXcEk/kpIGk27wB3XjkHuORz9fQ1NQBAIQZHnRfKlYFSSB83oTjr0456E9K+ddQ1Cx0D9qb7XezW9haRvGryMP3cZezVeSMYBLY3HAGcngGvofzViuN0krRrK/liOQcF8cFT2BA6euOhznnte+H3h7xXPaya/pUV49rEYo5zPIsrLkY3MhXP8Rwc4JOOpoA8T8earpetfHvww+kXttqMMc9nG7RNui3m4LldwypGHGSvHJzlga+k4U2RjOQxA3AuXwcAcE/T+veuMT4c+EjeWN2mgpb3uklYdOLXEqovlkyIQA2G5JY5BJO7OTk11c0CzSpcRgSM6bEkJyIhhjuXHPOQDgjIx6UAePftEW8F34E0bU5Ih9riv/JRwSNqvG5dSucZzGmc5IIxnrn0H4f2FvY/DHw3b2uIIZLCGVwWYktKod8HOQS7kj0zwOlXtf8ADWj+LdIXTtdtDqMdrIshRXaImUIeRtYdnPGcc+1aOmWdtZadbWdtbeTaWkaRWqsSSsaoAPvfMCBkc88c9aAJYXKFFeSWTzeULREbQFGd2BgHOTzjrjtXyTr/APa/wr1zxT4WtifsepQiOKWVAxaEk7XDFBlvLaWNiuBlnxyor64t0aMzK0ryAyFl3jG0HBwD3GSf5dq+btZ0rxF8V/HumC/8K33h/TYFVbl7mMqyo0pLESNECSxbCoQwByeBuIAPTPgh4WXQPAVrey2yJeamn2qSQ7WfaxOxdwH3NgRgCSQWbp0Hoc4lWKT97L88ihDEilkB2juCCM5JJHQn0qaV/LieTaz7VJ2qMk47AetU7VVFmlmt2RKq8YKb1UNjGORx90n2oA8K/ZrSGVPFEU6xujm0GxwCGP749D16Z/CveY0AtvsoWKVUPlOrLtG3HTAGDwRxwPp0rC8P+DvDvgqaZPD2mNbzXqjzFFxI4YJ0J3sQAC/bnnoa6KFflErR+XLIoMi7s4OPyJ7Z9hQA2OPbOfLn/dINhgAXCHAxjAyOOx9anqsJpmulCKjwMAdwzwCDg56HkdufmHTHNmgAooooAKY0MTRmNo0KE5KlRgnOen15oooAfTY40iUqgwCxb8Scn9TRRQA6iiigBiRRxbvLjVNzFm2jGSepPvTgqqWIUAsckgdT0/oKKKAE8tPN8zYvmY27sc49M+lOoooARVVRhQAMk8DueTS0UUAf/9k=","timestamp":1651744158542}

**Comment by f0ng** [comment]
麻烦师傅加下微信，f-f0ng

**Comment by f0ng** [comment]
可以正常识别，原因在于jdk版本，可以尝试更换jdk版本，启动jdk版本是jdk10，burp的扩展jdk版本是jdk8
